### ISSUE TITLE
Latest Posts returns All posts

### ISSUE THREAD

**Issue by apraditya** [dim0627/hugo_theme_aglaus#12]
In the `single` partial, Is there a way to only lists some of the posts rather than all of them? Thanks

**Comment by dim0627** [comment]
Sorry, This theme does not have list filtering feature.
I think it would be better to have it forked and edited.

**Comment by dim0627** [comment]
Oh sorry, I did not understand the meaning of the issue.
That is bug.
I'll fix after.

**Comment by apraditya** [comment]
How's it going? Thanks

**Comment by dim0627** [comment]
I'm sorry to the late fix.
I fixed this issue in the latest commits.
Please try again!

**Comment by apraditya** [comment]
Hey, sorry I just tried and it still list all posts. I exported from wordpress with [SchumacherFM/wordpress-to-hugo-exporter](https://github.com/SchumacherFM/wordpress-to-hugo-exporter). Do you think it's related? Here's a sample meta it generates:

```yaml
---
title: 'My Favourite Books'
author: Adinda
type: post
date: 2016-08-10T08:08:54+00:00
url: /archives/2681-my-favourite-books/
categories:
  - Books

---
```

Do you think it will help if I create an example repo?
